/**
 * Curated backlink-prospects library — manually compiled from working SEO
 * practice. Every entry is a real, currently-operating site as of 2026-05.
 *
 * Fields:
 *   - da: rough Moz Domain Authority estimate, mostly to sort by trust
 *   - cost: "free" | "freemium" | "paid"
 *   - linkType: "dofollow" | "nofollow" | "mixed" (mixed = depends on
 *     placement)
 *   - difficulty: 1-5, rough effort to actually land the link
 *   - submissionTime: rough minutes-per-submission
 *   - niches: tags for filtering (empty = "any niche")
 *   - howTo: 3-6 line plain-English instructions
 *
 * The goal is to be MORE useful than a 2010-era "top 100 directories" PDF
 * by being honest about DA, niche fit, and effort. Spammy / penalized
 * directories are deliberately excluded.
 */

export type ProspectCategory =
  | "directory"
  | "guest-post"
  | "resource"
  | "forum"
  | "haro-style"
  | "web2"
  | "qa"
  | "profile"
  | "bookmark"
  | "podcast"
  | "press"
  | "edu-gov"
  | "saas-tool"
  | "ecommerce"
  | "local"
  | "industry"
  | "developer"
  | "creator";

export type Prospect = {
  name: string;
  url: string;
  category: ProspectCategory;
  da: number;
  cost: "free" | "freemium" | "paid";
  linkType: "dofollow" | "nofollow" | "mixed";
  difficulty: 1 | 2 | 3 | 4 | 5;
  submissionTimeMin: number;
  niches: string[];
  /** ISO 3166-1 alpha-2 country codes. Empty = global. */
  countries: string[];
  description: string;
  howTo: string[];
};

export const PROSPECTS: Prospect[] = [
  // ============================================================
  // GENERAL HIGH-AUTHORITY DIRECTORIES
  // ============================================================
  {
    name: "DMOZ Successor (Curlie)",
    url: "https://curlie.org/docs/en/add.html",
    category: "directory",
    da: 65,
    cost: "free",
    linkType: "nofollow",
    difficulty: 4,
    submissionTimeMin: 15,
    niches: [],
    countries: [],
    description:
      "The community-edited successor to DMOZ. Editors review every submission, can take weeks.",
    howTo: [
      "Find the most-specific category matching your site.",
      "Click 'suggest a site' under that exact category.",
      "Write a neutral, factual 25-30 word description.",
      "Wait 2-8 weeks. Don't resubmit; multiple submissions get rejected.",
    ],
  },
  {
    name: "Best of the Web (BOTW)",
    url: "https://botw.org/",
    category: "directory",
    da: 55,
    cost: "paid",
    linkType: "dofollow",
    difficulty: 2,
    submissionTimeMin: 10,
    niches: [],
    countries: [],
    description:
      "Paid editorial review directory ($150 lifetime). Has survived 20+ years.",
    howTo: [
      "Pick the deepest matching category — top categories are saturated.",
      "Write a 100-word description focused on what users get.",
      "Pay the one-time fee. Approval in 5-10 business days.",
    ],
  },
  {
    name: "Jasmine Directory",
    url: "https://www.jasminedirectory.com/",
    category: "directory",
    da: 51,
    cost: "paid",
    linkType: "dofollow",
    difficulty: 2,
    submissionTimeMin: 10,
    niches: [],
    countries: [],
    description:
      "Editorial directory, $60/year. Good fit for legitimate businesses.",
    howTo: [
      "Choose category carefully — moving costs extra.",
      "Description should mention products/services concretely.",
      "Annual renewal required to keep the link active.",
    ],
  },
  {
    name: "Hotfrog",
    url: "https://www.hotfrog.com/",
    category: "directory",
    da: 76,
    cost: "free",
    linkType: "nofollow",
    difficulty: 1,
    submissionTimeMin: 8,
    niches: ["local", "services"],
    countries: [],
    description:
      "Worldwide business directory. NAP citation value > link value.",
    howTo: [
      "Add your business with consistent name, address, phone.",
      "Verify by email/phone.",
      "Add photos and full description for ranking inside Hotfrog.",
    ],
  },
  {
    name: "Brownbook",
    url: "https://www.brownbook.net/",
    category: "directory",
    da: 67,
    cost: "free",
    linkType: "nofollow",
    difficulty: 1,
    submissionTimeMin: 5,
    niches: ["local", "services"],
    countries: [],
    description: "Global business directory. Fast approval.",
    howTo: [
      "Click 'add a business'.",
      "Fill NAP exactly as it appears on your site + GBP.",
      "Verify by email.",
    ],
  },

  // ============================================================
  // GUEST POST / EDITORIAL PLATFORMS
  // ============================================================
  {
    name: "Medium",
    url: "https://medium.com/",
    category: "guest-post",
    da: 96,
    cost: "free",
    linkType: "dofollow",
    difficulty: 1,
    submissionTimeMin: 60,
    niches: [],
    countries: [],
    description:
      "Free publishing platform. Direct links in body are dofollow. Republish your blog posts here after canonical lag.",
    howTo: [
      "Wait 2-3 weeks after publishing on your site (let Google index original first).",
      "Set canonical to your original URL — Medium honors it.",
      "Include 1-2 contextual links back to relevant pages.",
      "Use 5 strategic tags.",
    ],
  },
  {
    name: "Dev.to",
    url: "https://dev.to/",
    category: "guest-post",
    da: 90,
    cost: "free",
    linkType: "dofollow",
    difficulty: 1,
    submissionTimeMin: 45,
    niches: ["saas", "developer", "tech"],
    countries: [],
    description:
      "Developer-focused publishing platform. Strong dofollow links from quality posts.",
    howTo: [
      "Canonical to your blog if cross-posting.",
      "Quality > quantity — 1500+ word technical posts perform best.",
      "Engage in comments to build profile authority.",
    ],
  },
  {
    name: "Hashnode",
    url: "https://hashnode.com/",
    category: "guest-post",
    da: 78,
    cost: "free",
    linkType: "dofollow",
    difficulty: 1,
    submissionTimeMin: 45,
    niches: ["saas", "developer", "tech"],
    countries: [],
    description:
      "Developer blog network. Can set a custom domain — links carry well.",
    howTo: [
      "Set your hashnode.dev subdomain to a memorable handle.",
      "Cross-post with canonical to your main blog.",
      "Use 3-5 niche tags, not generic ones.",
    ],
  },
  {
    name: "Substack",
    url: "https://substack.com/",
    category: "guest-post",
    da: 92,
    cost: "free",
    linkType: "dofollow",
    difficulty: 2,
    submissionTimeMin: 60,
    niches: [],
    countries: [],
    description:
      "Newsletter platform. Articles indexed by Google, links are dofollow.",
    howTo: [
      "Pick a niche, write recurringly — Google needs to see consistency.",
      "Include 2-3 contextual links per post to your relevant pages.",
      "Cross-link with other Substacks in your niche for compound effect.",
    ],
  },
  {
    name: "LinkedIn Articles",
    url: "https://www.linkedin.com/post/new",
    category: "guest-post",
    da: 98,
    cost: "free",
    linkType: "nofollow",
    difficulty: 1,
    submissionTimeMin: 45,
    niches: ["b2b", "saas", "services"],
    countries: [],
    description:
      "LinkedIn long-form posts. Nofollow but still drive brand traffic + indirect SEO.",
    howTo: [
      "Post 2x/week minimum to build distribution.",
      "Link to your site from author profile + one body link.",
      "Don't paywall the value — give it away in the post.",
    ],
  },

  // ============================================================
  // HARO-STYLE / EXPERT QUOTE PLATFORMS
  // ============================================================
  {
    name: "Connectively (formerly HARO)",
    url: "https://www.connectively.us/",
    category: "haro-style",
    da: 78,
    cost: "freemium",
    linkType: "dofollow",
    difficulty: 3,
    submissionTimeMin: 20,
    niches: [],
    countries: [],
    description:
      "Journalist queries 3x/day. Replied-and-quoted = links from Forbes / WSJ / etc.",
    howTo: [
      "Subscribe to your relevant beats only — signal-to-noise matters.",
      "Reply in <2 hours from email arrival; first 5 responses get read.",
      "300-word max with a 1-line bio + clean credentials.",
    ],
  },
  {
    name: "Qwoted",
    url: "https://www.qwoted.com/",
    category: "haro-style",
    da: 65,
    cost: "freemium",
    linkType: "dofollow",
    difficulty: 3,
    submissionTimeMin: 20,
    niches: [],
    countries: [],
    description: "Alternative to HARO/Connectively. Smaller, less competition.",
    howTo: [
      "Build out your expert profile completely (photo, bio, topics).",
      "Reply fast and quotable — journalists copy-paste.",
      "Free tier limits per-month replies; upgrade if landing 2+/month.",
    ],
  },
  {
    name: "SourceBottle",
    url: "https://www.sourcebottle.com/",
    category: "haro-style",
    da: 50,
    cost: "free",
    linkType: "dofollow",
    difficulty: 2,
    submissionTimeMin: 15,
    niches: [],
    countries: [],
    description: "Australia/UK/US journalist source platform.",
    howTo: [
      "Select 1-3 categories matching your expertise.",
      "Same fast-reply discipline as HARO.",
      "Include link + photo in reply for higher pickup rate.",
    ],
  },
  {
    name: "JournoRequests",
    url: "https://twitter.com/journorequest",
    category: "haro-style",
    da: 99,
    cost: "free",
    linkType: "nofollow",
    difficulty: 3,
    submissionTimeMin: 10,
    niches: [],
    countries: [],
    description: "Twitter hashtag #journorequest — journalists asking for sources.",
    howTo: [
      "Set a saved search for '#journorequest [your niche]'.",
      "Reply within 30 mins, DM if they prefer.",
      "Link to a relevant page on your site, not your homepage.",
    ],
  },

  // ============================================================
  // RESOURCE PAGES (ASK-FOR-INCLUSION)
  // ============================================================
  {
    name: "Awesome Lists (GitHub)",
    url: "https://github.com/sindresorhus/awesome",
    category: "resource",
    da: 100,
    cost: "free",
    linkType: "dofollow",
    difficulty: 4,
    submissionTimeMin: 30,
    niches: ["developer", "tech", "saas"],
    countries: [],
    description:
      "Curated topic lists on GitHub. Getting added to a relevant awesome-X list = forever dofollow link from DA 100.",
    howTo: [
      "Find the awesome-list for your niche (awesome-react, awesome-seo, etc.).",
      "Read CONTRIBUTING.md carefully — every list has rules.",
      "Open a PR adding your resource with the exact required format.",
      "Be polite in PR conversation, fix feedback promptly.",
    ],
  },
  {
    name: "Product Hunt",
    url: "https://www.producthunt.com/",
    category: "resource",
    da: 91,
    cost: "free",
    linkType: "nofollow",
    difficulty: 3,
    submissionTimeMin: 60,
    niches: ["saas", "tech"],
    countries: [],
    description:
      "Launch platform. The PH page links are nofollow, but successful launches drive press coverage which is dofollow.",
    howTo: [
      "Plan launch day for Tuesday-Thursday for max visibility.",
      "Prepare a punchy tagline (40 chars), hero image, GIF demo.",
      "Notify your network 1 week before; ask for first-hour upvotes.",
      "Reply to every comment in the first 24 hours.",
    ],
  },
  {
    name: "BetaList",
    url: "https://betalist.com/",
    category: "resource",
    da: 76,
    cost: "freemium",
    linkType: "dofollow",
    difficulty: 2,
    submissionTimeMin: 30,
    niches: ["saas"],
    countries: [],
    description: "Pre-launch / early-stage SaaS listings.",
    howTo: [
      "Submit before official launch — that's the platform's angle.",
      "Free tier waits ~3 months; $89 upgrades for instant publication.",
      "Tag carefully — 'AI', 'SaaS' broad tags get drowned out.",
    ],
  },
  {
    name: "AlternativeTo",
    url: "https://alternativeto.net/",
    category: "resource",
    da: 87,
    cost: "free",
    linkType: "nofollow",
    difficulty: 2,
    submissionTimeMin: 30,
    niches: ["saas", "tech"],
    countries: [],
    description:
      "User-submitted alternatives to existing software. High intent traffic.",
    howTo: [
      "Find the main competitor's page on AlternativeTo.",
      "Submit your software as an alternative with screenshots + description.",
      "Editor review takes 1-2 weeks.",
    ],
  },
  {
    name: "Capterra",
    url: "https://www.capterra.com/",
    category: "resource",
    da: 90,
    cost: "freemium",
    linkType: "nofollow",
    difficulty: 2,
    submissionTimeMin: 30,
    niches: ["saas", "b2b"],
    countries: [],
    description: "Software review site. Paid placement available.",
    howTo: [
      "Create free vendor profile.",
      "Solicit reviews from existing customers (Capterra has a tool for this).",
      "Paid spots in 'top-rated' lists are PPC-style, not link value.",
    ],
  },
  {
    name: "G2",
    url: "https://www.g2.com/",
    category: "resource",
    da: 91,
    cost: "freemium",
    linkType: "nofollow",
    difficulty: 2,
    submissionTimeMin: 30,
    niches: ["saas", "b2b"],
    countries: [],
    description: "B2B software reviews. Heavy trust signal.",
    howTo: [
      "Claim your profile, fill it completely.",
      "Reach 10+ verified reviews for free badges + featured placement.",
      "Reply to reviews professionally — sales prospects read these.",
    ],
  },
  {
    name: "TrustPilot",
    url: "https://www.trustpilot.com/",
    category: "resource",
    da: 93,
    cost: "freemium",
    linkType: "nofollow",
    difficulty: 1,
    submissionTimeMin: 20,
    niches: [],
    countries: [],
    description: "Consumer reviews. Drives indirect SEO via brand trust.",
    howTo: [
      "Claim your profile, verify domain.",
      "Send post-purchase invites to customers via TrustPilot's API.",
      "Embed widget on your site for site-rich-snippet stars.",
    ],
  },

  // ============================================================
  // FORUMS / COMMUNITIES (PROFILE + CONTEXTUAL)
  // ============================================================
  {
    name: "Reddit",
    url: "https://www.reddit.com/",
    category: "forum",
    da: 100,
    cost: "free",
    linkType: "nofollow",
    difficulty: 3,
    submissionTimeMin: 20,
    niches: [],
    countries: [],
    description:
      "Massive forum. Nofollow but in 40% of LLM citations. Indirect SEO via brand + AI visibility.",
    howTo: [
      "Build karma in 3-5 niche subreddits over weeks before linking.",
      "1 self-promo per 10 helpful comments is the unwritten rule.",
      "When linking, give context — naked URLs get downvoted.",
    ],
  },
  {
    name: "Hacker News",
    url: "https://news.ycombinator.com/",
    category: "forum",
    da: 91,
    cost: "free",
    linkType: "nofollow",
    difficulty: 4,
    submissionTimeMin: 5,
    niches: ["saas", "tech", "developer"],
    countries: [],
    description:
      "Tech founder/dev community. Front-page = thousands of visitors + press pickup.",
    howTo: [
      "Submit 'Show HN: <product> — <one-line value prop>'.",
      "Reply to every comment in first 4 hours, even negative ones.",
      "Be authentic; HN sniffs out marketing speak instantly.",
    ],
  },
  {
    name: "IndieHackers",
    url: "https://www.indiehackers.com/",
    category: "forum",
    da: 80,
    cost: "free",
    linkType: "dofollow",
    difficulty: 2,
    submissionTimeMin: 60,
    niches: ["saas", "tech"],
    countries: [],
    description:
      "Indie founder community. Posts can contain dofollow links to your site.",
    howTo: [
      "Set up product profile + share genuine MRR/growth numbers.",
      "Long-form posts about your build journey get traction.",
      "Reply to others' posts before pushing your own.",
    ],
  },
  {
    name: "Quora",
    url: "https://www.quora.com/",
    category: "qa",
    da: 92,
    cost: "free",
    linkType: "nofollow",
    difficulty: 2,
    submissionTimeMin: 20,
    niches: [],
    countries: [],
    description: "Q&A site. Strong topic authority signals + LLM citation source.",
    howTo: [
      "Find questions with 1k+ views in your niche, ranking pages.",
      "Write 200-500 word genuine answers with 1 contextual link max.",
      "Build credit by answering 10+ without linking first.",
    ],
  },
  {
    name: "Stack Exchange Network",
    url: "https://stackexchange.com/sites",
    category: "qa",
    da: 95,
    cost: "free",
    linkType: "nofollow",
    difficulty: 3,
    submissionTimeMin: 30,
    niches: [],
    countries: [],
    description:
      "Stack Overflow + 170+ niche Q&A sites (SuperUser, Webmasters, Mathematics, etc.).",
    howTo: [
      "Pick the niche site matching your expertise — SO has high standards.",
      "Earn 10+ rep before posting links; new accounts get rejected.",
      "Link only when it adds value beyond the answer text.",
    ],
  },

  // ============================================================
  // LOCAL CITATIONS (NAP-FOCUSED, FREE)
  // ============================================================
  {
    name: "Google Business Profile",
    url: "https://www.google.com/business/",
    category: "local",
    da: 100,
    cost: "free",
    linkType: "nofollow",
    difficulty: 1,
    submissionTimeMin: 20,
    niches: ["local"],
    countries: [],
    description:
      "Non-negotiable for local SEO. Drives Map Pack rankings and indirect SEO.",
    howTo: [
      "Claim and verify your listing (postcard, phone, or video).",
      "Add categories, photos, services, hours.",
      "Post 1+ weekly update for ranking signal.",
    ],
  },
  {
    name: "Apple Business Connect",
    url: "https://businessconnect.apple.com/",
    category: "local",
    da: 100,
    cost: "free",
    linkType: "nofollow",
    difficulty: 1,
    submissionTimeMin: 15,
    niches: ["local"],
    countries: [],
    description: "Apple Maps + Siri listing. Free, often missed.",
    howTo: [
      "Sign in with Apple ID, claim your business.",
      "Verify by phone or document upload.",
      "Add showcases, photos, links to update regularly.",
    ],
  },
  {
    name: "Bing Places",
    url: "https://www.bingplaces.com/",
    category: "local",
    da: 92,
    cost: "free",
    linkType: "nofollow",
    difficulty: 1,
    submissionTimeMin: 10,
    niches: ["local"],
    countries: [],
    description: "Bing + Microsoft Maps + Cortana. Import from GBP saves time.",
    howTo: [
      "Sign in, choose 'Import from Google'.",
      "Verify by phone or postcard.",
      "Add Bing-specific photos / categories where they differ from GBP.",
    ],
  },
  {
    name: "Yelp",
    url: "https://biz.yelp.com/",
    category: "local",
    da: 93,
    cost: "freemium",
    linkType: "nofollow",
    difficulty: 1,
    submissionTimeMin: 15,
    niches: ["local", "services", "restaurant"],
    countries: ["US", "CA", "GB", "AU"],
    description:
      "US-heavy local directory. Reviews drive trust; don't game them.",
    howTo: [
      "Claim profile, fill 100%.",
      "Solicit reviews softly — Yelp filters aggressive solicitation.",
      "Reply to every review, especially negative ones.",
    ],
  },
  {
    name: "Foursquare City Guide",
    url: "https://foursquare.com/",
    category: "local",
    da: 91,
    cost: "free",
    linkType: "nofollow",
    difficulty: 1,
    submissionTimeMin: 10,
    niches: ["local"],
    countries: [],
    description:
      "Powers many third-party Map data. NAP citation value > direct traffic.",
    howTo: [
      "Claim venue via Foursquare for Business.",
      "Verify by email or phone.",
      "Update categories + hours.",
    ],
  },
  {
    name: "MapQuest",
    url: "https://www.mapquest.com/",
    category: "local",
    da: 92,
    cost: "free",
    linkType: "nofollow",
    difficulty: 1,
    submissionTimeMin: 10,
    niches: ["local"],
    countries: [],
    description: "Auto-pulls from Yext / Factual data feeds. Worth verifying.",
    howTo: [
      "Search for your business; if missing, submit via 'add a place'.",
      "Verify ownership.",
    ],
  },
  {
    name: "Yellow Pages (US)",
    url: "https://accounts.yellowpages.com/register",
    category: "local",
    da: 88,
    cost: "freemium",
    linkType: "nofollow",
    difficulty: 1,
    submissionTimeMin: 10,
    niches: ["local"],
    countries: ["US"],
    description: "Legacy directory still pulled by aggregators.",
    howTo: [
      "Create free YP account.",
      "Claim listing or add new.",
      "Verify by phone.",
    ],
  },
  {
    name: "Manta",
    url: "https://www.manta.com/",
    category: "local",
    da: 73,
    cost: "free",
    linkType: "nofollow",
    difficulty: 1,
    submissionTimeMin: 10,
    niches: ["local", "b2b"],
    countries: ["US"],
    description: "Small-business directory, US-focused.",
    howTo: ["Search for your business, claim or add.", "Verify by email."],
  },
  {
    name: "Better Business Bureau",
    url: "https://www.bbb.org/",
    category: "local",
    da: 92,
    cost: "paid",
    linkType: "nofollow",
    difficulty: 2,
    submissionTimeMin: 30,
    niches: ["local", "services", "b2b"],
    countries: [],
    description:
      "Trust signal more than backlink. Accreditation is paid (~$500/yr).",
    howTo: [
      "Apply for accreditation if you can pass their standards.",
      "Profile is free without accreditation but limited.",
    ],
  },
  {
    name: "Chamber of Commerce (your city)",
    url: "https://www.uschamber.com/co",
    category: "local",
    da: 73,
    cost: "paid",
    linkType: "dofollow",
    difficulty: 2,
    submissionTimeMin: 60,
    niches: ["local", "b2b"],
    countries: [],
    description:
      "Local chamber memberships often include a dofollow directory listing.",
    howTo: [
      "Google '[your city] chamber of commerce'.",
      "Join — usually $200-1000/year.",
      "Request a directory listing as part of membership.",
    ],
  },

  // ============================================================
  // PODCAST DIRECTORIES (FOR PODCAST OWNERS)
  // ============================================================
  {
    name: "Apple Podcasts",
    url: "https://podcasters.apple.com/",
    category: "podcast",
    da: 100,
    cost: "free",
    linkType: "dofollow",
    difficulty: 2,
    submissionTimeMin: 30,
    niches: ["creator", "media"],
    countries: [],
    description: "Largest podcast directory. RSS-based submission.",
    howTo: [
      "Set up your podcast RSS feed.",
      "Submit via Podcasters Connect.",
      "Approval in 2-7 days.",
    ],
  },
  {
    name: "Spotify for Podcasters",
    url: "https://podcasters.spotify.com/",
    category: "podcast",
    da: 95,
    cost: "free",
    linkType: "dofollow",
    difficulty: 1,
    submissionTimeMin: 15,
    niches: ["creator", "media"],
    countries: [],
    description: "Free hosting + distribution. Show notes carry links.",
    howTo: [
      "Sign up free.",
      "Add show name, art, RSS or upload directly.",
      "Include 1-2 links in every episode's show notes.",
    ],
  },
  {
    name: "Listen Notes",
    url: "https://www.listennotes.com/",
    category: "podcast",
    da: 84,
    cost: "free",
    linkType: "dofollow",
    difficulty: 1,
    submissionTimeMin: 5,
    niches: ["creator", "media"],
    countries: [],
    description: "Podcast search engine. Indexed by Google.",
    howTo: [
      "Submit your RSS feed.",
      "Auto-syncs new episodes.",
    ],
  },

  // ============================================================
  // PRESS / NEWS WIRES
  // ============================================================
  {
    name: "PR.com",
    url: "https://www.pr.com/",
    category: "press",
    da: 84,
    cost: "freemium",
    linkType: "nofollow",
    difficulty: 1,
    submissionTimeMin: 20,
    niches: [],
    countries: [],
    description: "Free press release distribution. Mostly nofollow.",
    howTo: [
      "Write a real news-worthy release (product launch, funding, hire).",
      "Use H1/H2 structure; one link in body, one in author bio.",
    ],
  },
  {
    name: "EIN Presswire",
    url: "https://www.einpresswire.com/",
    category: "press",
    da: 88,
    cost: "paid",
    linkType: "nofollow",
    difficulty: 2,
    submissionTimeMin: 30,
    niches: [],
    countries: [],
    description: "Paid PR distribution — wider syndication than free options.",
    howTo: [
      "$99-499 per release tier.",
      "Picked up by Google News, Yahoo News, AP affiliate sites.",
    ],
  },
  {
    name: "OpenPR",
    url: "https://www.openpr.com/",
    category: "press",
    da: 60,
    cost: "free",
    linkType: "nofollow",
    difficulty: 1,
    submissionTimeMin: 15,
    niches: [],
    countries: [],
    description: "Free press release with link.",
    howTo: [
      "Free tier limits link count; one is enough.",
      "Editorial review for spam — write a real release.",
    ],
  },

  // ============================================================
  // PROFILE CREATION SITES
  // ============================================================
  {
    name: "About.me",
    url: "https://about.me/",
    category: "profile",
    da: 90,
    cost: "free",
    linkType: "dofollow",
    difficulty: 1,
    submissionTimeMin: 10,
    niches: [],
    countries: [],
    description: "Personal landing page with dofollow link.",
    howTo: [
      "Claim your handle, fill bio + photo.",
      "Link directly to your site in the headline area.",
    ],
  },
  {
    name: "GitHub Profile",
    url: "https://github.com/",
    category: "profile",
    da: 100,
    cost: "free",
    linkType: "dofollow",
    difficulty: 1,
    submissionTimeMin: 15,
    niches: ["developer", "saas"],
    countries: [],
    description: "Profile README + bio link, both dofollow.",
    howTo: [
      "Create a repo named after your username — its README shows on your profile.",
      "Add link in profile bio field.",
      "Make your repos public + contribute to gain authority.",
    ],
  },
  {
    name: "Behance",
    url: "https://www.behance.net/",
    category: "profile",
    da: 92,
    cost: "free",
    linkType: "dofollow",
    difficulty: 1,
    submissionTimeMin: 20,
    niches: ["creator", "design"],
    countries: [],
    description: "Adobe portfolio site. Strong design niche.",
    howTo: [
      "Create profile, link to portfolio.",
      "Upload 5+ projects to look credible.",
    ],
  },
  {
    name: "Dribbble",
    url: "https://dribbble.com/",
    category: "profile",
    da: 92,
    cost: "free",
    linkType: "dofollow",
    difficulty: 2,
    submissionTimeMin: 20,
    niches: ["creator", "design"],
    countries: [],
    description: "Designer community. Invite-only to post.",
    howTo: [
      "Apply for invite or get one from existing member.",
      "Profile link is dofollow.",
    ],
  },
  {
    name: "AngelList / Wellfound",
    url: "https://wellfound.com/",
    category: "profile",
    da: 87,
    cost: "free",
    linkType: "nofollow",
    difficulty: 2,
    submissionTimeMin: 30,
    niches: ["saas", "b2b"],
    countries: [],
    description: "Startup + hiring platform. Company profile + jobs.",
    howTo: [
      "Create company profile, link to site.",
      "Listing jobs adds activity signal.",
    ],
  },
  {
    name: "Crunchbase",
    url: "https://www.crunchbase.com/",
    category: "profile",
    da: 91,
    cost: "freemium",
    linkType: "nofollow",
    difficulty: 2,
    submissionTimeMin: 30,
    niches: ["saas", "b2b"],
    countries: [],
    description: "Company database. Funding + team data.",
    howTo: [
      "Create unclaimed profile via 'add organization'.",
      "Claim by verifying domain email.",
      "Keep funding rounds + team current.",
    ],
  },

  // ============================================================
  // SOCIAL BOOKMARKING
  // ============================================================
  {
    name: "Pinterest",
    url: "https://www.pinterest.com/",
    category: "bookmark",
    da: 94,
    cost: "free",
    linkType: "nofollow",
    difficulty: 1,
    submissionTimeMin: 5,
    niches: ["ecommerce", "creator", "local"],
    countries: [],
    description: "Visual bookmark. Drives traffic + Google indexes pins.",
    howTo: [
      "Set up business account, verify domain.",
      "Create 10+ boards in your niche.",
      "Pin original images from your site weekly.",
    ],
  },
  {
    name: "Flipboard",
    url: "https://flipboard.com/",
    category: "bookmark",
    da: 91,
    cost: "free",
    linkType: "nofollow",
    difficulty: 1,
    submissionTimeMin: 10,
    niches: ["creator", "media"],
    countries: [],
    description: "Magazine-style content curation.",
    howTo: [
      "Create magazine in your niche.",
      "Flip your articles + others' in a 1:3 ratio.",
    ],
  },
  {
    name: "Slashdot",
    url: "https://slashdot.org/",
    category: "bookmark",
    da: 90,
    cost: "free",
    linkType: "nofollow",
    difficulty: 4,
    submissionTimeMin: 5,
    niches: ["tech", "saas", "developer"],
    countries: [],
    description: "Long-running tech news aggregator. Hard to land.",
    howTo: [
      "Submit story via firehose.",
      "Most submissions never make the front page.",
    ],
  },

  // ============================================================
  // EDU / GOV STYLE OPPORTUNITIES
  // ============================================================
  {
    name: "Scholarship Program (your industry)",
    url: "https://www.scholarships.com/",
    category: "edu-gov",
    da: 0,
    cost: "paid",
    linkType: "dofollow",
    difficulty: 5,
    submissionTimeMin: 240,
    niches: [],
    countries: [],
    description:
      "Create a $1k-5k scholarship, submit to .edu scholarship pages. Earns dofollow .edu links.",
    howTo: [
      "Build scholarship page on your site with eligibility + how to apply.",
      "Cold-email university financial aid offices: scholarship details + link.",
      "Pay out the scholarship — Google can spot fakes.",
    ],
  },
  {
    name: "Wikipedia",
    url: "https://en.wikipedia.org/",
    category: "edu-gov",
    da: 100,
    cost: "free",
    linkType: "nofollow",
    difficulty: 5,
    submissionTimeMin: 60,
    niches: [],
    countries: [],
    description:
      "Nofollow but huge brand + AI Overview citation source. Hard to land.",
    howTo: [
      "Don't try to create your own page — it'll be deleted.",
      "Look for existing topic articles missing a citation, add your source.",
      "Build edit history first; cold edits from new accounts get reverted.",
    ],
  },
  {
    name: "Wikidata",
    url: "https://www.wikidata.org/",
    category: "edu-gov",
    da: 95,
    cost: "free",
    linkType: "nofollow",
    difficulty: 3,
    submissionTimeMin: 30,
    niches: [],
    countries: [],
    description:
      "Structured data feeds Wikipedia + Google Knowledge Panel.",
    howTo: [
      "Create item for your entity (company, person, product).",
      "Add 'official website' property pointing to your URL.",
      "Cite reliable sources in the references.",
    ],
  },

  // ============================================================
  // NICHE: SAAS / TECH
  // ============================================================
  {
    name: "SaaSHub",
    url: "https://www.saashub.com/",
    category: "saas-tool",
    da: 60,
    cost: "free",
    linkType: "dofollow",
    difficulty: 2,
    submissionTimeMin: 20,
    niches: ["saas"],
    countries: [],
    description: "SaaS comparison site. Easy listings.",
    howTo: ["Submit via 'add a service'.", "Editorial review in 1-2 weeks."],
  },
  {
    name: "GetApp",
    url: "https://www.getapp.com/",
    category: "saas-tool",
    da: 87,
    cost: "free",
    linkType: "nofollow",
    difficulty: 2,
    submissionTimeMin: 30,
    niches: ["saas", "b2b"],
    countries: [],
    description: "Gartner-owned (with Capterra + Software Advice).",
    howTo: [
      "Free vendor profile.",
      "Reviews + filled profile drive ranking inside GetApp.",
    ],
  },
  {
    name: "Software Advice",
    url: "https://www.softwareadvice.com/",
    category: "saas-tool",
    da: 86,
    cost: "free",
    linkType: "nofollow",
    difficulty: 2,
    submissionTimeMin: 30,
    niches: ["saas", "b2b"],
    countries: [],
    description: "Gartner B2B software review site.",
    howTo: ["Same vendor program as Capterra/GetApp.", "One claim covers all 3."],
  },
  {
    name: "Slant",
    url: "https://www.slant.co/",
    category: "saas-tool",
    da: 78,
    cost: "free",
    linkType: "dofollow",
    difficulty: 3,
    submissionTimeMin: 30,
    niches: ["saas", "tech", "developer"],
    countries: [],
    description: "Community-ranked best-tools-for-X lists.",
    howTo: [
      "Find topics matching your tool.",
      "Add your tool as an option with pros/cons.",
      "Encourage users to upvote (don't astroturf).",
    ],
  },
  {
    name: "StackShare",
    url: "https://stackshare.io/",
    category: "saas-tool",
    da: 80,
    cost: "free",
    linkType: "dofollow",
    difficulty: 2,
    submissionTimeMin: 30,
    niches: ["saas", "developer"],
    countries: [],
    description: "Companies share their tech stacks.",
    howTo: [
      "Add your tool/service.",
      "Encourage customers to add you to their public stack.",
    ],
  },
  {
    name: "Indie Hackers Products",
    url: "https://www.indiehackers.com/products",
    category: "saas-tool",
    da: 80,
    cost: "free",
    linkType: "dofollow",
    difficulty: 2,
    submissionTimeMin: 30,
    niches: ["saas"],
    countries: [],
    description: "Indie products listings with revenue transparency.",
    howTo: [
      "Add product, share genuine revenue numbers.",
      "Engage in the forums to drive profile visits.",
    ],
  },
  {
    name: "Tools.fyi",
    url: "https://tools.fyi/",
    category: "saas-tool",
    da: 35,
    cost: "free",
    linkType: "dofollow",
    difficulty: 1,
    submissionTimeMin: 10,
    niches: ["saas"],
    countries: [],
    description: "Newer SaaS directory. Easy to land.",
    howTo: ["Submit tool details.", "Editorial in days."],
  },
  {
    name: "Saaspedia",
    url: "https://saaspedia.org/",
    category: "saas-tool",
    da: 40,
    cost: "free",
    linkType: "dofollow",
    difficulty: 1,
    submissionTimeMin: 10,
    niches: ["saas"],
    countries: [],
    description: "Small SaaS directory.",
    howTo: ["Add product."],
  },
  {
    name: "FuturePedia",
    url: "https://www.futurepedia.io/",
    category: "saas-tool",
    da: 73,
    cost: "freemium",
    linkType: "dofollow",
    difficulty: 2,
    submissionTimeMin: 20,
    niches: ["saas", "ai"],
    countries: [],
    description: "AI tools directory. High intent traffic.",
    howTo: [
      "Free submission queue is slow (4-8 weeks).",
      "$49 paid expedites to 3-5 days.",
    ],
  },
  {
    name: "There's An AI For That (TAAFT)",
    url: "https://theresanaiforthat.com/",
    category: "saas-tool",
    da: 78,
    cost: "freemium",
    linkType: "dofollow",
    difficulty: 2,
    submissionTimeMin: 20,
    niches: ["saas", "ai"],
    countries: [],
    description: "Largest AI tools directory.",
    howTo: ["Submit via 'add tool'.", "Paid options for faster review."],
  },
  {
    name: "AI Tools Directory",
    url: "https://aitoolsdirectory.com/",
    category: "saas-tool",
    da: 45,
    cost: "free",
    linkType: "dofollow",
    difficulty: 1,
    submissionTimeMin: 10,
    niches: ["saas", "ai"],
    countries: [],
    description: "Mid-size AI tools directory.",
    howTo: ["Submit tool with logo, description, link."],
  },

  // ============================================================
  // E-COMMERCE
  // ============================================================
  {
    name: "Etsy",
    url: "https://www.etsy.com/",
    category: "ecommerce",
    da: 92,
    cost: "freemium",
    linkType: "nofollow",
    difficulty: 1,
    submissionTimeMin: 30,
    niches: ["ecommerce"],
    countries: [],
    description: "Handmade marketplace. Link from shop profile to your site.",
    howTo: [
      "Set up shop, link your domain in the 'about' section.",
      "Drive customer browse to your own site via profile.",
    ],
  },
  {
    name: "Houzz",
    url: "https://www.houzz.com/",
    category: "ecommerce",
    da: 91,
    cost: "freemium",
    linkType: "nofollow",
    difficulty: 2,
    submissionTimeMin: 30,
    niches: ["ecommerce", "local", "services"],
    countries: [],
    description: "Home design + services platform.",
    howTo: [
      "Set up pro account if home-related.",
      "Profile carries link + photos drive traffic.",
    ],
  },
  {
    name: "Trustpilot",
    url: "https://www.trustpilot.com/",
    category: "ecommerce",
    da: 93,
    cost: "freemium",
    linkType: "nofollow",
    difficulty: 1,
    submissionTimeMin: 20,
    niches: ["ecommerce"],
    countries: [],
    description: "Reviews drive rich-snippet stars + trust.",
    howTo: [
      "Claim business profile.",
      "Embed widget on your site for stars in SERP.",
    ],
  },

  // ============================================================
  // CREATOR / MEDIA / VIDEO
  // ============================================================
  {
    name: "YouTube",
    url: "https://www.youtube.com/",
    category: "creator",
    da: 100,
    cost: "free",
    linkType: "nofollow",
    difficulty: 1,
    submissionTimeMin: 30,
    niches: ["creator", "media"],
    countries: [],
    description:
      "Channel description + video descriptions both accept links. Indirect SEO via brand + AI citations.",
    howTo: [
      "Add your URL to the channel description (visible without click).",
      "Each video description carries links — top of description is most clicked.",
      "Optimize titles for YouTube search; YT is the 2nd biggest search engine.",
    ],
  },
  {
    name: "Vimeo",
    url: "https://vimeo.com/",
    category: "creator",
    da: 95,
    cost: "freemium",
    linkType: "nofollow",
    difficulty: 1,
    submissionTimeMin: 20,
    niches: ["creator", "media"],
    countries: [],
    description: "Higher quality video alternative.",
    howTo: ["Create channel, link in profile.", "Video descriptions allow links."],
  },
  {
    name: "TikTok Bio",
    url: "https://www.tiktok.com/",
    category: "creator",
    da: 95,
    cost: "free",
    linkType: "nofollow",
    difficulty: 2,
    submissionTimeMin: 20,
    niches: ["creator", "ecommerce"],
    countries: [],
    description: "Bio link unlocks at 1k followers.",
    howTo: [
      "Build to 1k followers first.",
      "Then add direct link to your bio.",
    ],
  },
  {
    name: "Instagram",
    url: "https://www.instagram.com/",
    category: "creator",
    da: 100,
    cost: "free",
    linkType: "nofollow",
    difficulty: 1,
    submissionTimeMin: 10,
    niches: ["creator", "ecommerce", "local"],
    countries: [],
    description: "Bio link available from account creation.",
    howTo: [
      "One link in bio — use link-in-bio aggregator (Linktree, etc.).",
      "Stories with link sticker drive direct traffic.",
    ],
  },

  // ============================================================
  // DEVELOPER COMMUNITY
  // ============================================================
  {
    name: "npm",
    url: "https://www.npmjs.com/",
    category: "developer",
    da: 92,
    cost: "free",
    linkType: "dofollow",
    difficulty: 2,
    submissionTimeMin: 30,
    niches: ["developer", "saas"],
    countries: [],
    description:
      "Package homepage field is dofollow. Useful for tool/library makers.",
    howTo: [
      "Publish an npm package, even a wrapper or CLI for your service.",
      "Set 'homepage' in package.json to your marketing site.",
    ],
  },
  {
    name: "PyPI",
    url: "https://pypi.org/",
    category: "developer",
    da: 91,
    cost: "free",
    linkType: "dofollow",
    difficulty: 2,
    submissionTimeMin: 30,
    niches: ["developer", "saas"],
    countries: [],
    description: "Python package index. Homepage link dofollow.",
    howTo: [
      "Publish package, set 'project_urls' = {'Homepage': 'https://...'}.",
    ],
  },
  {
    name: "Docker Hub",
    url: "https://hub.docker.com/",
    category: "developer",
    da: 89,
    cost: "free",
    linkType: "dofollow",
    difficulty: 2,
    submissionTimeMin: 30,
    niches: ["developer"],
    countries: [],
    description: "Container image registry. Repo description carries links.",
    howTo: [
      "Push image, add detailed README via web UI.",
      "Link to docs / marketing site.",
    ],
  },
  {
    name: "VSCode Marketplace",
    url: "https://marketplace.visualstudio.com/",
    category: "developer",
    da: 95,
    cost: "free",
    linkType: "dofollow",
    difficulty: 3,
    submissionTimeMin: 60,
    niches: ["developer"],
    countries: [],
    description: "Publish a VSCode extension with link to your site.",
    howTo: [
      "Build extension (.vsix).",
      "Publisher account + README with marketing-site link.",
    ],
  },
  {
    name: "WordPress Plugin Directory",
    url: "https://wordpress.org/plugins/",
    category: "developer",
    da: 95,
    cost: "free",
    linkType: "dofollow",
    difficulty: 3,
    submissionTimeMin: 240,
    niches: ["developer"],
    countries: [],
    description: "Free plugin = dofollow link from a DA 95 page.",
    howTo: [
      "Build a free WordPress plugin that solves one focused problem.",
      "Submit via wordpress.org with valid plugin name + tested with current WP.",
      "Approval can take 2-8 weeks.",
    ],
  },
  {
    name: "Chrome Web Store",
    url: "https://chrome.google.com/webstore/",
    category: "developer",
    da: 100,
    cost: "paid",
    linkType: "dofollow",
    difficulty: 3,
    submissionTimeMin: 120,
    niches: ["developer"],
    countries: [],
    description:
      "Publish a Chrome extension — listing page links to your site.",
    howTo: [
      "$5 one-time developer fee.",
      "Build a useful extension, follow review guidelines.",
      "Approval in 1-3 days.",
    ],
  },

  // ============================================================
  // WEB 2.0 / FREE SUB-DOMAINS
  // ============================================================
  {
    name: "Wix",
    url: "https://www.wix.com/",
    category: "web2",
    da: 94,
    cost: "free",
    linkType: "dofollow",
    difficulty: 1,
    submissionTimeMin: 60,
    niches: [],
    countries: [],
    description:
      "Free sub-domain site (yourname.wixsite.com). Outgoing links dofollow.",
    howTo: [
      "Create free site at yourname.wixsite.com.",
      "Build 5-7 pages of original content related to your niche.",
      "Link to your main site contextually in articles.",
    ],
  },
  {
    name: "WordPress.com",
    url: "https://wordpress.com/",
    category: "web2",
    da: 94,
    cost: "free",
    linkType: "dofollow",
    difficulty: 1,
    submissionTimeMin: 60,
    niches: [],
    countries: [],
    description: "Free blog at yourname.wordpress.com.",
    howTo: [
      "Build out 5-10 niche posts.",
      "Link back to your main site in body copy.",
    ],
  },
  {
    name: "Blogger",
    url: "https://www.blogger.com/",
    category: "web2",
    da: 100,
    cost: "free",
    linkType: "dofollow",
    difficulty: 1,
    submissionTimeMin: 60,
    niches: [],
    countries: [],
    description: "Google's free blog platform. blogspot.com sub-domain.",
    howTo: [
      "Create blog under Google account.",
      "Same content strategy: real posts + contextual links.",
    ],
  },
  {
    name: "Tumblr",
    url: "https://www.tumblr.com/",
    category: "web2",
    da: 100,
    cost: "free",
    linkType: "nofollow",
    difficulty: 1,
    submissionTimeMin: 30,
    niches: [],
    countries: [],
    description: "Microblog platform. Links nofollow but brand signal.",
    howTo: ["Create profile, link in bio + posts."],
  },
  {
    name: "Notion (public pages)",
    url: "https://www.notion.so/",
    category: "web2",
    da: 92,
    cost: "free",
    linkType: "dofollow",
    difficulty: 1,
    submissionTimeMin: 30,
    niches: [],
    countries: [],
    description: "Publish Notion pages publicly — they index and carry links.",
    howTo: [
      "Build a Notion page about a topic in your niche.",
      "Share publicly (toggle 'Share to web').",
      "Submit URL to Google Search Console for indexing.",
    ],
  },
  {
    name: "Webflow CMS (free)",
    url: "https://webflow.com/",
    category: "web2",
    da: 87,
    cost: "freemium",
    linkType: "dofollow",
    difficulty: 2,
    submissionTimeMin: 90,
    niches: [],
    countries: [],
    description: "Free webflow.io subdomain. Higher design ceiling than Wix.",
    howTo: [
      "Build site on webflow.io subdomain.",
      "Outgoing links dofollow.",
    ],
  },

  // ============================================================
  // INDUSTRY-SPECIFIC (a sampler — extend per niche)
  // ============================================================
  {
    name: "ProductHunt Maker Stories",
    url: "https://www.producthunt.com/stories",
    category: "industry",
    da: 91,
    cost: "free",
    linkType: "dofollow",
    difficulty: 3,
    submissionTimeMin: 120,
    niches: ["saas"],
    countries: [],
    description: "Featured maker stories. Editorial.",
    howTo: [
      "Build relationship via PH community first.",
      "Pitch a maker story angle (lesson, milestone, build-in-public).",
    ],
  },
  {
    name: "Designer News",
    url: "https://www.designernews.co/",
    category: "industry",
    da: 75,
    cost: "free",
    linkType: "nofollow",
    difficulty: 3,
    submissionTimeMin: 5,
    niches: ["creator", "design"],
    countries: [],
    description: "Design community news aggregator.",
    howTo: ["Submit interesting design content.", "Hard to land front page."],
  },
  {
    name: "Lobsters",
    url: "https://lobste.rs/",
    category: "industry",
    da: 75,
    cost: "free",
    linkType: "nofollow",
    difficulty: 5,
    submissionTimeMin: 5,
    niches: ["developer", "tech"],
    countries: [],
    description: "Tech community, invite-only to submit.",
    howTo: ["Need invite from existing member."],
  },
  {
    name: "DEV Community Tags",
    url: "https://dev.to/tags",
    category: "industry",
    da: 90,
    cost: "free",
    linkType: "dofollow",
    difficulty: 1,
    submissionTimeMin: 60,
    niches: ["developer"],
    countries: [],
    description: "Posts under niche tags get topical authority.",
    howTo: ["Tag 4-5 specific tags, not generic.", "Quality > quantity."],
  },
  {
    name: "Forrester (mention)",
    url: "https://www.forrester.com/",
    category: "industry",
    da: 89,
    cost: "free",
    linkType: "nofollow",
    difficulty: 5,
    submissionTimeMin: 60,
    niches: ["b2b", "saas"],
    countries: [],
    description:
      "Analyst mentions in reports drive massive trust. Rarely free.",
    howTo: [
      "Submit briefing requests via Forrester's analyst program.",
      "Need genuine differentiator + paying customers to be considered.",
    ],
  },
  {
    name: "TripAdvisor",
    url: "https://www.tripadvisor.com/",
    category: "industry",
    da: 93,
    cost: "free",
    linkType: "nofollow",
    difficulty: 1,
    submissionTimeMin: 30,
    niches: ["local", "restaurant", "travel"],
    countries: [],
    description: "Travel + restaurants directory.",
    howTo: ["Claim listing as business owner.", "Reply to all reviews."],
  },
  {
    name: "Healthgrades",
    url: "https://www.healthgrades.com/",
    category: "industry",
    da: 88,
    cost: "free",
    linkType: "nofollow",
    difficulty: 1,
    submissionTimeMin: 30,
    niches: ["local", "healthcare"],
    countries: [],
    description: "Doctor + practice directory.",
    howTo: ["Claim listing.", "Verify credentials.", "Fill profile completely."],
  },
  {
    name: "Avvo",
    url: "https://www.avvo.com/",
    category: "industry",
    da: 86,
    cost: "free",
    linkType: "nofollow",
    difficulty: 1,
    submissionTimeMin: 30,
    niches: ["local", "legal"],
    countries: [],
    description: "Lawyer directory + Q&A.",
    howTo: ["Claim profile, fill completely.", "Answer questions for visibility."],
  },
  {
    name: "Houzz Pro",
    url: "https://www.houzz.com/pro",
    category: "industry",
    da: 91,
    cost: "freemium",
    linkType: "nofollow",
    difficulty: 1,
    submissionTimeMin: 30,
    niches: ["local", "construction", "design"],
    countries: [],
    description: "Home pro listing.",
    howTo: ["Claim or create profile.", "Upload project photos."],
  },
  {
    name: "Thumbtack",
    url: "https://www.thumbtack.com/",
    category: "industry",
    da: 87,
    cost: "free",
    linkType: "nofollow",
    difficulty: 1,
    submissionTimeMin: 30,
    niches: ["local", "services"],
    countries: [],
    description: "Local services marketplace.",
    howTo: ["Sign up as pro.", "Verify business.", "Optimize for keywords inside Thumbtack."],
  },
  {
    name: "Angi (formerly Angie's List)",
    url: "https://www.angi.com/",
    category: "industry",
    da: 87,
    cost: "freemium",
    linkType: "nofollow",
    difficulty: 1,
    submissionTimeMin: 30,
    niches: ["local", "services"],
    countries: [],
    description: "Home services reviews + directory.",
    howTo: ["Free profile available.", "Paid leads optional."],
  },

  // ============================================================
  // INDIA — local directories + classifieds
  // ============================================================
  {
    name: "Justdial",
    url: "https://www.justdial.com/",
    category: "local",
    da: 71,
    cost: "freemium",
    linkType: "nofollow",
    difficulty: 1,
    submissionTimeMin: 15,
    niches: ["local", "services"],
    countries: ["IN"],
    description: "India's biggest local directory + lead-gen platform.",
    howTo: [
      "Sign up via 'List your business'.",
      "Verify by phone (OTP).",
      "Free listing limited; paid tiers unlock leads + ranking.",
    ],
  },
  {
    name: "Sulekha",
    url: "https://www.sulekha.com/",
    category: "local",
    da: 67,
    cost: "freemium",
    linkType: "nofollow",
    difficulty: 1,
    submissionTimeMin: 15,
    niches: ["local", "services"],
    countries: ["IN"],
    description: "India local services + classifieds. Strong category coverage.",
    howTo: [
      "Choose business category — Sulekha is highly category-routed.",
      "Verify phone, fill detailed profile.",
    ],
  },
  {
    name: "IndiaMart",
    url: "https://seller.indiamart.com/",
    category: "ecommerce",
    da: 80,
    cost: "freemium",
    linkType: "nofollow",
    difficulty: 1,
    submissionTimeMin: 30,
    niches: ["ecommerce", "b2b", "local"],
    countries: ["IN"],
    description: "India's largest B2B marketplace.",
    howTo: [
      "Create free seller account.",
      "Add company info, product catalog.",
      "Paid 'TrustSEAL' tier accelerates buyer leads.",
    ],
  },
  {
    name: "TradeIndia",
    url: "https://www.tradeindia.com/",
    category: "ecommerce",
    da: 73,
    cost: "freemium",
    linkType: "nofollow",
    difficulty: 1,
    submissionTimeMin: 20,
    niches: ["ecommerce", "b2b"],
    countries: ["IN"],
    description: "India B2B + exports marketplace.",
    howTo: ["Free seller account.", "Verify business + add catalog."],
  },
  {
    name: "Cylex India",
    url: "https://www.cylex.in/",
    category: "local",
    da: 41,
    cost: "free",
    linkType: "nofollow",
    difficulty: 1,
    submissionTimeMin: 10,
    niches: ["local"],
    countries: ["IN"],
    description: "Cylex India local directory.",
    howTo: ["Free listing, NAP-focused."],
  },
  {
    name: "AskLaila",
    url: "https://www.asklaila.com/",
    category: "local",
    da: 48,
    cost: "free",
    linkType: "nofollow",
    difficulty: 1,
    submissionTimeMin: 10,
    niches: ["local"],
    countries: ["IN"],
    description: "India local search engine. City-focused.",
    howTo: ["Submit business via 'Add free listing'."],
  },
  {
    name: "TradesFolks",
    url: "https://www.tradesfolks.com/",
    category: "local",
    da: 28,
    cost: "free",
    linkType: "dofollow",
    difficulty: 1,
    submissionTimeMin: 8,
    niches: ["local", "services"],
    countries: ["IN"],
    description: "Indian tradesmen + services directory.",
    howTo: ["Free listing with NAP."],
  },
  {
    name: "GrotalSearch",
    url: "https://www.grotal.com/",
    category: "local",
    da: 38,
    cost: "free",
    linkType: "nofollow",
    difficulty: 1,
    submissionTimeMin: 10,
    niches: ["local"],
    countries: ["IN"],
    description: "India local business search.",
    howTo: ["Add free listing, verify by phone."],
  },
  {
    name: "Yalwa India",
    url: "https://www.yalwa.in/",
    category: "local",
    da: 40,
    cost: "free",
    linkType: "nofollow",
    difficulty: 1,
    submissionTimeMin: 10,
    niches: ["local"],
    countries: ["IN"],
    description: "Yalwa India business directory.",
    howTo: ["Free listing."],
  },
  {
    name: "Indiacatalog",
    url: "https://www.indiacatalog.com/",
    category: "directory",
    da: 32,
    cost: "free",
    linkType: "dofollow",
    difficulty: 1,
    submissionTimeMin: 10,
    niches: [],
    countries: ["IN"],
    description: "India business catalog.",
    howTo: ["Submit business with details."],
  },

  // ============================================================
  // UNITED KINGDOM
  // ============================================================
  {
    name: "Yell.com",
    url: "https://www.yell.com/",
    category: "local",
    da: 80,
    cost: "freemium",
    linkType: "nofollow",
    difficulty: 1,
    submissionTimeMin: 15,
    niches: ["local"],
    countries: ["GB"],
    description: "UK Yellow Pages successor.",
    howTo: [
      "Free basic listing via 'Get listed'.",
      "Verify by phone.",
      "Paid tiers for more visibility.",
    ],
  },
  {
    name: "Cylex UK",
    url: "https://www.cylex-uk.co.uk/",
    category: "local",
    da: 50,
    cost: "free",
    linkType: "nofollow",
    difficulty: 1,
    submissionTimeMin: 10,
    niches: ["local"],
    countries: ["GB"],
    description: "UK Cylex directory.",
    howTo: ["Add free listing with NAP."],
  },
  {
    name: "FreeIndex",
    url: "https://www.freeindex.co.uk/",
    category: "local",
    da: 56,
    cost: "free",
    linkType: "dofollow",
    difficulty: 1,
    submissionTimeMin: 15,
    niches: ["local"],
    countries: ["GB"],
    description: "Free UK business directory with reviews.",
    howTo: ["Free listing.", "Solicit reviews for ranking inside FreeIndex."],
  },
  {
    name: "Thomson Local",
    url: "https://www.thomsonlocal.com/",
    category: "local",
    da: 60,
    cost: "freemium",
    linkType: "nofollow",
    difficulty: 1,
    submissionTimeMin: 10,
    niches: ["local"],
    countries: ["GB"],
    description: "Legacy UK directory.",
    howTo: ["Free basic listing."],
  },
  {
    name: "Scoot UK",
    url: "https://www.scoot.co.uk/",
    category: "local",
    da: 51,
    cost: "free",
    linkType: "nofollow",
    difficulty: 1,
    submissionTimeMin: 10,
    niches: ["local"],
    countries: ["GB"],
    description: "UK local search.",
    howTo: ["Add free listing."],
  },
  {
    name: "Touch Local",
    url: "https://www.touchlocal.com/",
    category: "local",
    da: 44,
    cost: "free",
    linkType: "nofollow",
    difficulty: 1,
    submissionTimeMin: 10,
    niches: ["local"],
    countries: ["GB"],
    description: "UK directory.",
    howTo: ["Free listing."],
  },
  {
    name: "Bizwiki UK",
    url: "https://www.bizwiki.co.uk/",
    category: "local",
    da: 48,
    cost: "free",
    linkType: "dofollow",
    difficulty: 1,
    submissionTimeMin: 10,
    niches: ["local"],
    countries: ["GB"],
    description: "UK Bizwiki directory.",
    howTo: ["Free listing with NAP."],
  },

  // ============================================================
  // CANADA
  // ============================================================
  {
    name: "Yellow Pages Canada",
    url: "https://www.yellowpages.ca/",
    category: "local",
    da: 82,
    cost: "freemium",
    linkType: "nofollow",
    difficulty: 1,
    submissionTimeMin: 10,
    niches: ["local"],
    countries: ["CA"],
    description: "Canadian Yellow Pages.",
    howTo: ["Free listing.", "Verify by phone."],
  },
  {
    name: "Canada411",
    url: "https://www.canada411.ca/",
    category: "local",
    da: 75,
    cost: "free",
    linkType: "nofollow",
    difficulty: 1,
    submissionTimeMin: 10,
    niches: ["local"],
    countries: ["CA"],
    description: "Canadian phone + business directory.",
    howTo: ["Submit free listing."],
  },
  {
    name: "Cylex Canada",
    url: "https://www.cylex-canada.ca/",
    category: "local",
    da: 45,
    cost: "free",
    linkType: "nofollow",
    difficulty: 1,
    submissionTimeMin: 10,
    niches: ["local"],
    countries: ["CA"],
    description: "Canada Cylex directory.",
    howTo: ["Free listing."],
  },
  {
    name: "Goldbook",
    url: "https://www.goldbook.ca/",
    category: "local",
    da: 44,
    cost: "free",
    linkType: "nofollow",
    difficulty: 1,
    submissionTimeMin: 10,
    niches: ["local"],
    countries: ["CA"],
    description: "Canadian local directory.",
    howTo: ["Free listing."],
  },
  {
    name: "Profile Canada",
    url: "https://www.profilecanada.com/",
    category: "local",
    da: 50,
    cost: "free",
    linkType: "nofollow",
    difficulty: 1,
    submissionTimeMin: 10,
    niches: ["local", "b2b"],
    countries: ["CA"],
    description: "Canadian business profiles.",
    howTo: ["Submit business profile."],
  },

  // ============================================================
  // AUSTRALIA
  // ============================================================
  {
    name: "True Local",
    url: "https://www.truelocal.com.au/",
    category: "local",
    da: 70,
    cost: "free",
    linkType: "nofollow",
    difficulty: 1,
    submissionTimeMin: 15,
    niches: ["local"],
    countries: ["AU"],
    description: "Australia local directory.",
    howTo: ["Free listing.", "Verify by phone."],
  },
  {
    name: "Yellow Pages AU",
    url: "https://www.yellowpages.com.au/",
    category: "local",
    da: 78,
    cost: "freemium",
    linkType: "nofollow",
    difficulty: 1,
    submissionTimeMin: 15,
    niches: ["local"],
    countries: ["AU"],
    description: "Australian YP.",
    howTo: ["Free basic listing.", "Sensis verification needed."],
  },
  {
    name: "Australian Business Directory",
    url: "https://www.dlook.com.au/",
    category: "local",
    da: 50,
    cost: "free",
    linkType: "nofollow",
    difficulty: 1,
    submissionTimeMin: 10,
    niches: ["local"],
    countries: ["AU"],
    description: "AU local directory.",
    howTo: ["Submit listing."],
  },
  {
    name: "Hotfrog Australia",
    url: "https://www.hotfrog.com.au/",
    category: "local",
    da: 65,
    cost: "free",
    linkType: "nofollow",
    difficulty: 1,
    submissionTimeMin: 10,
    niches: ["local"],
    countries: ["AU"],
    description: "Hotfrog AU edition.",
    howTo: ["Same as global Hotfrog."],
  },
  {
    name: "StartLocal Australia",
    url: "https://www.startlocal.com.au/",
    category: "local",
    da: 48,
    cost: "free",
    linkType: "nofollow",
    difficulty: 1,
    submissionTimeMin: 10,
    niches: ["local"],
    countries: ["AU"],
    description: "Australia local search.",
    howTo: ["Free listing."],
  },

  // ============================================================
  // GERMANY
  // ============================================================
  {
    name: "Gelbe Seiten",
    url: "https://www.gelbeseiten.de/",
    category: "local",
    da: 82,
    cost: "freemium",
    linkType: "nofollow",
    difficulty: 1,
    submissionTimeMin: 15,
    niches: ["local"],
    countries: ["DE"],
    description: "Germany's Yellow Pages.",
    howTo: ["Free basic listing.", "Verify by phone."],
  },
  {
    name: "Das Örtliche",
    url: "https://www.dasoertliche.de/",
    category: "local",
    da: 78,
    cost: "freemium",
    linkType: "nofollow",
    difficulty: 1,
    submissionTimeMin: 15,
    niches: ["local"],
    countries: ["DE"],
    description: "German local directory.",
    howTo: ["Free listing.", "Verify by phone."],
  },
  {
    name: "11880.com",
    url: "https://www.11880.com/",
    category: "local",
    da: 70,
    cost: "freemium",
    linkType: "nofollow",
    difficulty: 1,
    submissionTimeMin: 10,
    niches: ["local"],
    countries: ["DE"],
    description: "Germany directory + 24/7 hotline.",
    howTo: ["Free profile."],
  },
  {
    name: "Cylex Deutschland",
    url: "https://www.cylex.de/",
    category: "local",
    da: 50,
    cost: "free",
    linkType: "nofollow",
    difficulty: 1,
    submissionTimeMin: 10,
    niches: ["local"],
    countries: ["DE"],
    description: "Cylex Germany.",
    howTo: ["Free listing."],
  },
  {
    name: "Branchenbuch.de",
    url: "https://www.branchenbuch.com/",
    category: "local",
    da: 55,
    cost: "free",
    linkType: "nofollow",
    difficulty: 1,
    submissionTimeMin: 10,
    niches: ["local"],
    countries: ["DE"],
    description: "German business directory.",
    howTo: ["Free listing."],
  },

  // ============================================================
  // FRANCE
  // ============================================================
  {
    name: "PagesJaunes",
    url: "https://www.pagesjaunes.fr/",
    category: "local",
    da: 88,
    cost: "freemium",
    linkType: "nofollow",
    difficulty: 1,
    submissionTimeMin: 15,
    niches: ["local"],
    countries: ["FR"],
    description: "France Yellow Pages.",
    howTo: ["Free basic listing.", "Verify by phone or mail."],
  },
  {
    name: "118 712",
    url: "https://www.118712.fr/",
    category: "local",
    da: 55,
    cost: "free",
    linkType: "nofollow",
    difficulty: 1,
    submissionTimeMin: 10,
    niches: ["local"],
    countries: ["FR"],
    description: "France directory + phone service.",
    howTo: ["Free listing."],
  },
  {
    name: "Le Bottin",
    url: "https://www.lebottin.fr/",
    category: "local",
    da: 50,
    cost: "free",
    linkType: "nofollow",
    difficulty: 1,
    submissionTimeMin: 10,
    niches: ["local"],
    countries: ["FR"],
    description: "France local directory.",
    howTo: ["Free listing."],
  },

  // ============================================================
  // SPAIN
  // ============================================================
  {
    name: "Páginas Amarillas",
    url: "https://www.paginasamarillas.es/",
    category: "local",
    da: 75,
    cost: "freemium",
    linkType: "nofollow",
    difficulty: 1,
    submissionTimeMin: 15,
    niches: ["local"],
    countries: ["ES"],
    description: "Spain Yellow Pages.",
    howTo: ["Free basic listing."],
  },
  {
    name: "QDQ.com",
    url: "https://www.qdq.com/",
    category: "local",
    da: 60,
    cost: "freemium",
    linkType: "nofollow",
    difficulty: 1,
    submissionTimeMin: 15,
    niches: ["local"],
    countries: ["ES"],
    description: "Spain local + advertising directory.",
    howTo: ["Free basic listing."],
  },

  // ============================================================
  // ITALY
  // ============================================================
  {
    name: "Pagine Gialle",
    url: "https://www.paginegialle.it/",
    category: "local",
    da: 80,
    cost: "freemium",
    linkType: "nofollow",
    difficulty: 1,
    submissionTimeMin: 15,
    niches: ["local"],
    countries: ["IT"],
    description: "Italy Yellow Pages.",
    howTo: ["Free basic listing.", "Verify by phone."],
  },
  {
    name: "ItaliaInformazioni",
    url: "https://www.italiainformazioni.it/",
    category: "local",
    da: 45,
    cost: "free",
    linkType: "nofollow",
    difficulty: 1,
    submissionTimeMin: 10,
    niches: ["local"],
    countries: ["IT"],
    description: "Italy local directory.",
    howTo: ["Free listing."],
  },

  // ============================================================
  // NETHERLANDS, NORDICS
  // ============================================================
  {
    name: "Telefoonboek.nl",
    url: "https://www.telefoonboek.nl/",
    category: "local",
    da: 70,
    cost: "free",
    linkType: "nofollow",
    difficulty: 1,
    submissionTimeMin: 10,
    niches: ["local"],
    countries: ["NL"],
    description: "Netherlands phonebook + business directory.",
    howTo: ["Free listing."],
  },
  {
    name: "Gouden Gids",
    url: "https://www.goudengids.nl/",
    category: "local",
    da: 75,
    cost: "freemium",
    linkType: "nofollow",
    difficulty: 1,
    submissionTimeMin: 15,
    niches: ["local"],
    countries: ["NL"],
    description: "Netherlands Yellow Pages.",
    howTo: ["Free basic listing."],
  },
  {
    name: "Gule Sider",
    url: "https://www.gulesider.no/",
    category: "local",
    da: 75,
    cost: "freemium",
    linkType: "nofollow",
    difficulty: 1,
    submissionTimeMin: 10,
    niches: ["local"],
    countries: ["NO"],
    description: "Norway Yellow Pages.",
    howTo: ["Free basic listing."],
  },
  {
    name: "Eniro",
    url: "https://www.eniro.se/",
    category: "local",
    da: 70,
    cost: "freemium",
    linkType: "nofollow",
    difficulty: 1,
    submissionTimeMin: 15,
    niches: ["local"],
    countries: ["SE", "NO", "DK"],
    description: "Sweden + Norway + Denmark directory.",
    howTo: ["Free basic listing."],
  },
  {
    name: "Fonecta Finder",
    url: "https://www.finder.fi/",
    category: "local",
    da: 65,
    cost: "freemium",
    linkType: "nofollow",
    difficulty: 1,
    submissionTimeMin: 15,
    niches: ["local"],
    countries: ["FI"],
    description: "Finland directory.",
    howTo: ["Free basic listing."],
  },

  // ============================================================
  // BRAZIL, LATAM
  // ============================================================
  {
    name: "Telelistas.net",
    url: "https://www.telelistas.net/",
    category: "local",
    da: 65,
    cost: "free",
    linkType: "nofollow",
    difficulty: 1,
    submissionTimeMin: 10,
    niches: ["local"],
    countries: ["BR"],
    description: "Brazil local directory.",
    howTo: ["Free listing."],
  },
  {
    name: "Páginas Amarillas Argentina",
    url: "https://www.paginasamarillas.com.ar/",
    category: "local",
    da: 65,
    cost: "freemium",
    linkType: "nofollow",
    difficulty: 1,
    submissionTimeMin: 15,
    niches: ["local"],
    countries: ["AR"],
    description: "Argentina YP.",
    howTo: ["Free basic listing."],
  },
  {
    name: "Sección Amarilla México",
    url: "https://www.seccionamarilla.com.mx/",
    category: "local",
    da: 70,
    cost: "freemium",
    linkType: "nofollow",
    difficulty: 1,
    submissionTimeMin: 15,
    niches: ["local"],
    countries: ["MX"],
    description: "Mexico YP.",
    howTo: ["Free basic listing."],
  },

  // ============================================================
  // JAPAN, KOREA, GREATER CHINA
  // ============================================================
  {
    name: "iTownPage (NTT)",
    url: "https://itp.ne.jp/",
    category: "local",
    da: 78,
    cost: "freemium",
    linkType: "nofollow",
    difficulty: 1,
    submissionTimeMin: 15,
    niches: ["local"],
    countries: ["JP"],
    description: "Japan NTT directory.",
    howTo: ["Free basic listing."],
  },
  {
    name: "Mapion",
    url: "https://www.mapion.co.jp/",
    category: "local",
    da: 75,
    cost: "free",
    linkType: "nofollow",
    difficulty: 1,
    submissionTimeMin: 10,
    niches: ["local"],
    countries: ["JP"],
    description: "Japan map + local directory.",
    howTo: ["Free listing."],
  },
  {
    name: "Naver Place",
    url: "https://place.map.naver.com/",
    category: "local",
    da: 95,
    cost: "free",
    linkType: "nofollow",
    difficulty: 1,
    submissionTimeMin: 20,
    niches: ["local"],
    countries: ["KR"],
    description: "Korea's dominant local directory (Naver). Must-have for KR.",
    howTo: [
      "Sign up for Naver Smart Place.",
      "Verify business by document upload.",
      "Korean-language profile required.",
    ],
  },
  {
    name: "Daum / Kakao Map",
    url: "https://map.kakao.com/",
    category: "local",
    da: 92,
    cost: "free",
    linkType: "nofollow",
    difficulty: 1,
    submissionTimeMin: 20,
    niches: ["local"],
    countries: ["KR"],
    description: "Korea's #2 map + local platform.",
    howTo: ["Submit business via Kakao for Business."],
  },
  {
    name: "Baidu Maps",
    url: "https://map.baidu.com/",
    category: "local",
    da: 91,
    cost: "free",
    linkType: "nofollow",
    difficulty: 2,
    submissionTimeMin: 30,
    niches: ["local"],
    countries: ["CN"],
    description: "China's #1 maps. Required for mainland China visibility.",
    howTo: [
      "Need a Chinese business license to claim.",
      "Verify by phone + documents.",
    ],
  },
  {
    name: "Dianping (大众点评)",
    url: "https://www.dianping.com/",
    category: "local",
    da: 87,
    cost: "freemium",
    linkType: "nofollow",
    difficulty: 2,
    submissionTimeMin: 30,
    niches: ["local", "restaurant"],
    countries: ["CN"],
    description: "China's Yelp equivalent. Massive for restaurants + services.",
    howTo: [
      "Need Chinese ID + business license.",
      "Verify in person at some cities.",
    ],
  },
  {
    name: "Hong Kong Yellow Pages",
    url: "https://www.yp.com.hk/",
    category: "local",
    da: 68,
    cost: "freemium",
    linkType: "nofollow",
    difficulty: 1,
    submissionTimeMin: 15,
    niches: ["local"],
    countries: ["HK"],
    description: "Hong Kong YP.",
    howTo: ["Free basic listing."],
  },

  // ============================================================
  // SOUTHEAST ASIA
  // ============================================================
  {
    name: "Yellow Pages Singapore",
    url: "https://www.yellowpages.com.sg/",
    category: "local",
    da: 65,
    cost: "freemium",
    linkType: "nofollow",
    difficulty: 1,
    submissionTimeMin: 15,
    niches: ["local"],
    countries: ["SG"],
    description: "Singapore YP.",
    howTo: ["Free basic listing."],
  },
  {
    name: "Yellow Pages Malaysia",
    url: "https://www.yellowpages.my/",
    category: "local",
    da: 55,
    cost: "freemium",
    linkType: "nofollow",
    difficulty: 1,
    submissionTimeMin: 15,
    niches: ["local"],
    countries: ["MY"],
    description: "Malaysia YP.",
    howTo: ["Free basic listing."],
  },
  {
    name: "Yellow Pages Philippines",
    url: "https://www.yellow-pages.ph/",
    category: "local",
    da: 50,
    cost: "free",
    linkType: "nofollow",
    difficulty: 1,
    submissionTimeMin: 10,
    niches: ["local"],
    countries: ["PH"],
    description: "Philippines YP.",
    howTo: ["Free listing."],
  },
  {
    name: "ThailandYP",
    url: "https://www.thailandyp.com/",
    category: "local",
    da: 45,
    cost: "free",
    linkType: "nofollow",
    difficulty: 1,
    submissionTimeMin: 10,
    niches: ["local"],
    countries: ["TH"],
    description: "Thailand YP.",
    howTo: ["Free listing."],
  },
  {
    name: "VietnamYellowPages",
    url: "https://www.vietnamyellowpages.com/",
    category: "local",
    da: 45,
    cost: "free",
    linkType: "nofollow",
    difficulty: 1,
    submissionTimeMin: 10,
    niches: ["local"],
    countries: ["VN"],
    description: "Vietnam YP.",
    howTo: ["Free listing."],
  },
  {
    name: "Yellow Pages Indonesia",
    url: "https://www.yellowpages.co.id/",
    category: "local",
    da: 55,
    cost: "freemium",
    linkType: "nofollow",
    difficulty: 1,
    submissionTimeMin: 15,
    niches: ["local"],
    countries: ["ID"],
    description: "Indonesia YP.",
    howTo: ["Free basic listing."],
  },

  // ============================================================
  // MIDDLE EAST + AFRICA
  // ============================================================
  {
    name: "Yellow Pages UAE",
    url: "https://www.yellowpages.ae/",
    category: "local",
    da: 60,
    cost: "freemium",
    linkType: "nofollow",
    difficulty: 1,
    submissionTimeMin: 15,
    niches: ["local"],
    countries: ["AE"],
    description: "UAE Yellow Pages.",
    howTo: ["Free basic listing."],
  },
  {
    name: "Yellow Pages Saudi Arabia",
    url: "https://www.yellowpages.com.sa/",
    category: "local",
    da: 55,
    cost: "freemium",
    linkType: "nofollow",
    difficulty: 1,
    submissionTimeMin: 15,
    niches: ["local"],
    countries: ["SA"],
    description: "Saudi YP.",
    howTo: ["Free basic listing."],
  },
  {
    name: "D&B Israel",
    url: "https://www.dbi.co.il/",
    category: "local",
    da: 60,
    cost: "free",
    linkType: "nofollow",
    difficulty: 1,
    submissionTimeMin: 10,
    niches: ["local", "b2b"],
    countries: ["IL"],
    description: "Israel business directory.",
    howTo: ["Free listing."],
  },
  {
    name: "Yellow Pages Turkey",
    url: "https://www.altinrehber.com.tr/",
    category: "local",
    da: 55,
    cost: "freemium",
    linkType: "nofollow",
    difficulty: 1,
    submissionTimeMin: 15,
    niches: ["local"],
    countries: ["TR"],
    description: "Turkey YP.",
    howTo: ["Free basic listing."],
  },
  {
    name: "Brabys (South Africa)",
    url: "https://www.brabys.com/",
    category: "local",
    da: 65,
    cost: "free",
    linkType: "nofollow",
    difficulty: 1,
    submissionTimeMin: 10,
    niches: ["local"],
    countries: ["ZA"],
    description: "South Africa local directory.",
    howTo: ["Free listing."],
  },
  {
    name: "Yellow Pages Nigeria",
    url: "https://www.vconnect.com/",
    category: "local",
    da: 55,
    cost: "freemium",
    linkType: "nofollow",
    difficulty: 1,
    submissionTimeMin: 15,
    niches: ["local"],
    countries: ["NG"],
    description: "Nigeria's biggest local directory (VConnect).",
    howTo: ["Free basic listing."],
  },

  // ============================================================
  // IRELAND, NEW ZEALAND, EU GENERAL
  // ============================================================
  {
    name: "Golden Pages Ireland",
    url: "https://www.goldenpages.ie/",
    category: "local",
    da: 75,
    cost: "freemium",
    linkType: "nofollow",
    difficulty: 1,
    submissionTimeMin: 15,
    niches: ["local"],
    countries: ["IE"],
    description: "Ireland YP.",
    howTo: ["Free basic listing."],
  },
  {
    name: "Finda New Zealand",
    url: "https://www.finda.co.nz/",
    category: "local",
    da: 60,
    cost: "free",
    linkType: "nofollow",
    difficulty: 1,
    submissionTimeMin: 10,
    niches: ["local"],
    countries: ["NZ"],
    description: "NZ local directory.",
    howTo: ["Free listing."],
  },
  {
    name: "Yellow NZ",
    url: "https://yellow.co.nz/",
    category: "local",
    da: 73,
    cost: "freemium",
    linkType: "nofollow",
    difficulty: 1,
    submissionTimeMin: 15,
    niches: ["local"],
    countries: ["NZ"],
    description: "NZ YP.",
    howTo: ["Free basic listing."],
  },
  {
    name: "Europages",
    url: "https://www.europages.com/",
    category: "local",
    da: 81,
    cost: "freemium",
    linkType: "nofollow",
    difficulty: 1,
    submissionTimeMin: 15,
    niches: ["b2b", "local"],
    countries: ["DE", "FR", "IT", "ES", "NL", "BE", "GB"],
    description: "Pan-European B2B + local directory.",
    howTo: ["Free basic listing.", "Multi-language profile."],
  },
];

export const CATEGORY_LABELS: Record<ProspectCategory, string> = {
  directory: "Business directories",
  "guest-post": "Guest post / cross-publish",
  resource: "Resource pages + launch platforms",
  forum: "Forums + communities",
  "haro-style": "Journalist source (HARO-style)",
  web2: "Free sub-domain sites (web 2.0)",
  qa: "Q&A platforms",
  profile: "Profile creation",
  bookmark: "Social bookmarking",
  podcast: "Podcast directories",
  press: "Press release wires",
  "edu-gov": "Edu / Gov opportunities",
  "saas-tool": "SaaS / tool directories",
  ecommerce: "E-commerce platforms",
  local: "Local citations (NAP)",
  industry: "Industry-specific",
  developer: "Developer ecosystem",
  creator: "Creator / video / social",
};

export const COUNTRY_LABELS: Record<string, string> = {
  US: "United States",
  CA: "Canada",
  GB: "United Kingdom",
  IE: "Ireland",
  AU: "Australia",
  NZ: "New Zealand",
  IN: "India",
  DE: "Germany",
  FR: "France",
  ES: "Spain",
  IT: "Italy",
  NL: "Netherlands",
  BE: "Belgium",
  SE: "Sweden",
  NO: "Norway",
  DK: "Denmark",
  FI: "Finland",
  PL: "Poland",
  TR: "Turkey",
  IL: "Israel",
  AE: "UAE",
  SA: "Saudi Arabia",
  ZA: "South Africa",
  NG: "Nigeria",
  BR: "Brazil",
  AR: "Argentina",
  MX: "Mexico",
  JP: "Japan",
  KR: "South Korea",
  CN: "China",
  HK: "Hong Kong",
  SG: "Singapore",
  MY: "Malaysia",
  PH: "Philippines",
  TH: "Thailand",
  VN: "Vietnam",
  ID: "Indonesia",
};

export const NICHE_LABELS: Record<string, string> = {
  saas: "SaaS",
  ecommerce: "E-commerce",
  local: "Local business",
  services: "Services",
  b2b: "B2B",
  developer: "Developer",
  creator: "Creator",
  tech: "Tech",
  ai: "AI",
  media: "Media",
  design: "Design",
  restaurant: "Restaurant / food",
  travel: "Travel",
  healthcare: "Healthcare",
  legal: "Legal",
  construction: "Construction",
};
