/**
 * GitHub PR generator for SEO fixes.
 *
 * For sites NOT on a CMS we have a write-bridge for (Next.js, custom code,
 * static sites in a Git repo), the cleanest way to apply SEO fixes is to
 * open a pull request. This module:
 *
 *   1) Builds a structured patch description from a list of suggestions
 *      (title rewrites, meta updates, schema additions, redirects, etc.)
 *   2) Uses the GitHub REST API (BYO PAT) to:
 *      - find the default branch SHA
 *      - create a new branch (`seo-fixes/<date>-<slug>`)
 *      - commit a structured changes manifest as a markdown file
 *      - open a PR with a checklist body
 *
 * The PR doesn't auto-edit application code — it lands a clear,
 * structured proposal the developer can act on. This avoids the failure
 * mode of generating bad code edits and forces a human review for free.
 *
 * BYO PAT: stored per-client in settings. Scope: `repo` for private
 * repos, `public_repo` for public ones.
 */

const GH_API = "https://api.github.com";

export type GhRepoTarget = {
  owner: string;
  repo: string;
  /** GitHub PAT with `repo` or `public_repo` scope. */
  token: string;
};

export type SeoFixSuggestion = {
  /** Short title describing the change. */
  title: string;
  /** URL on the live site this fix applies to. */
  targetUrl?: string;
  /** Type tag — used for grouping in the PR body. */
  type:
    | "title_rewrite"
    | "meta_description_rewrite"
    | "h1_rewrite"
    | "schema_markup"
    | "internal_link"
    | "redirect"
    | "robots"
    | "sitemap"
    | "general";
  /** The suggested value (e.g. new title). For schema, the full JSON-LD. */
  suggestedValue: string;
  /** Optional rationale shown alongside the change. */
  rationale?: string;
};

export type PrResult =
  | { ok: true; prNumber: number; prUrl: string; branch: string; manifestPath: string }
  | { ok: false; error: string };

async function gh<T>(
  path: string,
  token: string,
  init?: RequestInit,
): Promise<{ ok: true; data: T } | { ok: false; error: string }> {
  const res = await fetch(`${GH_API}${path}`, {
    ...init,
    headers: {
      accept: "application/vnd.github+json",
      authorization: `Bearer ${token}`,
      "x-github-api-version": "2022-11-28",
      ...(init?.body ? { "content-type": "application/json" } : {}),
      ...(init?.headers ?? {}),
    },
  });
  if (!res.ok) {
    const t = await res.text();
    return { ok: false, error: `GitHub ${res.status}: ${t.slice(0, 300)}` };
  }
  return { ok: true, data: (await res.json()) as T };
}

function dateSlug(): string {
  const d = new Date();
  const pad = (n: number) => String(n).padStart(2, "0");
  return `${d.getFullYear()}${pad(d.getMonth() + 1)}${pad(d.getDate())}-${pad(d.getHours())}${pad(d.getMinutes())}`;
}

function buildManifestMarkdown(
  fixes: SeoFixSuggestion[],
  domain: string,
): string {
  const grouped = new Map<string, SeoFixSuggestion[]>();
  for (const f of fixes) {
    const list = grouped.get(f.type) ?? [];
    list.push(f);
    grouped.set(f.type, list);
  }
  const sectionLabel: Record<string, string> = {
    title_rewrite: "Title rewrites",
    meta_description_rewrite: "Meta description rewrites",
    h1_rewrite: "H1 rewrites",
    schema_markup: "Schema markup additions",
    internal_link: "Internal link additions",
    redirect: "Redirects to add",
    robots: "robots.txt changes",
    sitemap: "Sitemap changes",
    general: "Other changes",
  };
  const lines: string[] = [
    `# SEO fixes for ${domain}`,
    "",
    `Generated by the SEO tool at ${new Date().toISOString()}.`,
    "",
    `**Total changes proposed:** ${fixes.length}`,
    "",
    "Each section below lists the change with the target URL (if any) and",
    "the suggested value. Apply via your CMS / template / repo as relevant.",
    "Tick the checkbox once each change is implemented.",
    "",
  ];
  for (const [type, list] of grouped) {
    lines.push(`## ${sectionLabel[type] ?? type} (${list.length})`);
    lines.push("");
    for (const f of list) {
      lines.push(`- [ ] **${f.title}**`);
      if (f.targetUrl) lines.push(`    - URL: \`${f.targetUrl}\``);
      lines.push(
        `    - Suggested: ${
          type === "schema_markup"
            ? "\n\n      ```json\n      " +
              f.suggestedValue.split("\n").join("\n      ") +
              "\n      ```\n"
            : `\`${f.suggestedValue.slice(0, 240)}${f.suggestedValue.length > 240 ? "…" : ""}\``
        }`,
      );
      if (f.rationale) lines.push(`    - Why: ${f.rationale}`);
      lines.push("");
    }
  }
  return lines.join("\n");
}

/**
 * Open a PR on the target repo with a structured SEO-fixes manifest. Does
 * NOT modify application code — just adds a markdown file under
 * `seo-fixes/<datestamp>.md` so the developer reviews and applies.
 */
export async function openSeoFixesPr(opts: {
  target: GhRepoTarget;
  /** Title of the pull request. */
  prTitle?: string;
  /** Optional base branch (defaults to repo's default branch). */
  baseBranch?: string;
  /** The list of fixes to include. */
  fixes: SeoFixSuggestion[];
  /** Public domain name being fixed (cosmetic — used in the PR body). */
  domain: string;
}): Promise<PrResult> {
  const { target, fixes, domain } = opts;
  if (fixes.length === 0)
    return { ok: false, error: "No fixes supplied — nothing to PR." };

  // Resolve repo + default branch
  const repoR = await gh<{
    default_branch: string;
    name: string;
  }>(`/repos/${target.owner}/${target.repo}`, target.token);
  if (!repoR.ok) return { ok: false, error: repoR.error };
  const baseBranch = opts.baseBranch ?? repoR.data.default_branch;

  // Get base branch SHA
  const refR = await gh<{ object: { sha: string } }>(
    `/repos/${target.owner}/${target.repo}/git/refs/heads/${encodeURIComponent(baseBranch)}`,
    target.token,
  );
  if (!refR.ok) return { ok: false, error: refR.error };
  const baseSha = refR.data.object.sha;

  // Create new branch
  const slug = dateSlug();
  const branchName = `seo-fixes/${slug}`;
  const newRefR = await gh(
    `/repos/${target.owner}/${target.repo}/git/refs`,
    target.token,
    {
      method: "POST",
      body: JSON.stringify({
        ref: `refs/heads/${branchName}`,
        sha: baseSha,
      }),
    },
  );
  if (!newRefR.ok) return { ok: false, error: newRefR.error };

  // Commit the manifest file
  const manifestMd = buildManifestMarkdown(fixes, domain);
  const manifestPath = `seo-fixes/${slug}.md`;
  const contentB64 = Buffer.from(manifestMd, "utf-8").toString("base64");
  const putR = await gh<{ commit: { sha: string } }>(
    `/repos/${target.owner}/${target.repo}/contents/${encodeURIComponent(manifestPath)}`,
    target.token,
    {
      method: "PUT",
      body: JSON.stringify({
        message: `chore(seo): add SEO fixes manifest ${slug}`,
        content: contentB64,
        branch: branchName,
      }),
    },
  );
  if (!putR.ok) return { ok: false, error: putR.error };

  // Open PR
  const prTitle = opts.prTitle ?? `SEO fixes — ${fixes.length} changes for ${domain}`;
  const prR = await gh<{ number: number; html_url: string }>(
    `/repos/${target.owner}/${target.repo}/pulls`,
    target.token,
    {
      method: "POST",
      body: JSON.stringify({
        title: prTitle,
        head: branchName,
        base: baseBranch,
        body: `Automated SEO fixes proposal generated from the SEO tool.

This PR adds **\`${manifestPath}\`** with a checklist of ${fixes.length} concrete changes (title rewrites, meta updates, schema additions, etc.).

The PR does NOT auto-edit application code — implement each change in the relevant template, CMS, or framework component, then tick the box and merge.

See the file for full details.`,
      }),
    },
  );
  if (!prR.ok) return { ok: false, error: prR.error };

  return {
    ok: true,
    prNumber: prR.data.number,
    prUrl: prR.data.html_url,
    branch: branchName,
    manifestPath,
  };
}
